# Generated by Django 4.2.4 on 2023-10-12 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Дата поимки в формате: ГГГГ-ММ-ДД', verbose_name='Дата поимки')),
                ('time', models.TimeField(blank=True, help_text='Введите время поимки(необязательное поле)', null=True, verbose_name='Время поимки')),
                ('temperature', models.IntegerField(default=0, verbose_name='Температура')),
                ('pressure', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Атмосферное давление')),
                ('humidity', models.IntegerField(default=0, verbose_name='Влажность')),
                ('wind_speed', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Скорость ветра')),
                ('wind_vector', models.CharField(default='Не определено', max_length=10, verbose_name='Направление ветра')),
                ('cloudy', models.IntegerField(default=0, verbose_name='Облачность')),
                ('type_of_fish', models.CharField(max_length=50, verbose_name='Вид пойманной рыбы')),
                ('description', models.CharField(blank=True, help_text='Можете описать особенности поимки рыбы или в целом про рыбалку(необязательное поле)', max_length=1000, verbose_name='Описание')),
                ('bait', models.CharField(blank=True, help_text='Название приманки(необязательное поле)', max_length=100, verbose_name='Приманка')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/catch', verbose_name='Изображение')),
                ('latitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='Координата широты')),
                ('longitude', models.DecimalField(decimal_places=5, default=0.0, max_digits=8, verbose_name='Координата долготы')),
            ],
        ),
    ]
