# Generated by Django 4.2.4 on 2023-10-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fish_app_django', '0006_alter_catch_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='fish_weight',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, null=True, verbose_name='Вес рыбы(необязательное поле)'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/catch', verbose_name='Вы можете добавить фотографию'),
        ),
    ]
