# Generated by Django 4.2.4 on 2023-10-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fish_app_django', '0008_alter_catch_fish_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='fish_weight',
            field=models.DecimalField(decimal_places=3, max_digits=8, null=True, verbose_name='Вес рыбы(необязательное поле)'),
        ),
    ]
