# Generated by Django 4.2.4 on 2023-10-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fish_app_django', '0009_alter_catch_fish_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catch',
            name='fish_weight',
            field=models.DecimalField(decimal_places=3, default=50, max_digits=8, verbose_name='Вес рыбы в граммах(необязательное поле)'),
        ),
    ]
