# Generated by Django 4.2.4 on 2023-10-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fish_app_django', '0010_alter_catch_fish_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='catch',
            name='description_weather',
            field=models.CharField(default='Не определено', max_length=200),
        ),
        migrations.AddField(
            model_name='catch',
            name='name_of_the_area',
            field=models.CharField(default='Не определено', max_length=50),
        ),
        migrations.AlterField(
            model_name='catch',
            name='description',
            field=models.CharField(blank=True, help_text='Можете описать особенности поимки рыбы или в целом про рыбалку(необязательное поле)', max_length=1000, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='catch',
            name='fish_weight',
            field=models.DecimalField(decimal_places=3, default=50, max_digits=15, verbose_name='Вес рыбы в граммах'),
        ),
    ]
